# Generated by Django 3.2.21 on 2023-10-19 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerandjob', '0002_applicationmodel_messagemodel_studentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='degree',
        ),
    ]
