# Generated by Django 3.2.12 on 2023-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('jobrole', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('applylink', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('lastdate', models.CharField(max_length=50)),
            ],
        ),
    ]
