# Generated by Django 3.2.21 on 2023-10-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerandjob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.FileField(upload_to='documents')),
                ('notificationid', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('postedby', models.CharField(max_length=500)),
                ('postedto', models.CharField(max_length=500)),
                ('mdate', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rno', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('passing', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='documents')),
                ('isHavingBacklogs', models.CharField(max_length=50)),
                ('knownLanguages', models.CharField(max_length=50)),
                ('ishavingyeargap', models.CharField(max_length=50)),
            ],
        ),
    ]
